# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(860, 422)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButton_15 = QtWidgets.QRadioButton(Form)
        self.radioButton_15.setObjectName("radioButton_15")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.radioButton_15)
        self.gridLayout_2.addWidget(self.radioButton_15, 2, 0, 1, 1)
        self.radioButton_13 = QtWidgets.QRadioButton(Form)
        self.radioButton_13.setObjectName("radioButton_13")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButton_13)
        self.gridLayout_2.addWidget(self.radioButton_13, 1, 5, 1, 1)
        self.radioButton_10 = QtWidgets.QRadioButton(Form)
        self.radioButton_10.setObjectName("radioButton_10")
        self.buttonGroup_2.addButton(self.radioButton_10)
        self.gridLayout_2.addWidget(self.radioButton_10, 1, 2, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(Form)
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_4)
        self.gridLayout_2.addWidget(self.radioButton_4, 0, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 3, 3, 1, 1)
        self.radioButton_7 = QtWidgets.QRadioButton(Form)
        self.radioButton_7.setObjectName("radioButton_7")
        self.buttonGroup.addButton(self.radioButton_7)
        self.gridLayout_2.addWidget(self.radioButton_7, 0, 6, 1, 1)
        self.radioButton_16 = QtWidgets.QRadioButton(Form)
        self.radioButton_16.setObjectName("radioButton_16")
        self.buttonGroup_3.addButton(self.radioButton_16)
        self.gridLayout_2.addWidget(self.radioButton_16, 2, 1, 1, 1)
        self.radioButton_14 = QtWidgets.QRadioButton(Form)
        self.radioButton_14.setObjectName("radioButton_14")
        self.buttonGroup_2.addButton(self.radioButton_14)
        self.gridLayout_2.addWidget(self.radioButton_14, 1, 6, 1, 1)
        self.radioButton_17 = QtWidgets.QRadioButton(Form)
        self.radioButton_17.setObjectName("radioButton_17")
        self.buttonGroup_3.addButton(self.radioButton_17)
        self.gridLayout_2.addWidget(self.radioButton_17, 2, 2, 1, 1)
        self.radioButton_11 = QtWidgets.QRadioButton(Form)
        self.radioButton_11.setObjectName("radioButton_11")
        self.buttonGroup_2.addButton(self.radioButton_11)
        self.gridLayout_2.addWidget(self.radioButton_11, 1, 3, 1, 1)
        self.radioButton_18 = QtWidgets.QRadioButton(Form)
        self.radioButton_18.setObjectName("radioButton_18")
        self.buttonGroup_3.addButton(self.radioButton_18)
        self.gridLayout_2.addWidget(self.radioButton_18, 2, 3, 1, 1)
        self.radioButton_9 = QtWidgets.QRadioButton(Form)
        self.radioButton_9.setObjectName("radioButton_9")
        self.buttonGroup_2.addButton(self.radioButton_9)
        self.gridLayout_2.addWidget(self.radioButton_9, 1, 1, 1, 1)
        self.radioButton_8 = QtWidgets.QRadioButton(Form)
        self.radioButton_8.setObjectName("radioButton_8")
        self.buttonGroup_2.addButton(self.radioButton_8)
        self.gridLayout_2.addWidget(self.radioButton_8, 1, 0, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(Form)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.gridLayout_2.addWidget(self.radioButton_3, 0, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup.addButton(self.radioButton)
        self.gridLayout.addWidget(self.radioButton, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(Form)
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup.addButton(self.radioButton_5)
        self.gridLayout_2.addWidget(self.radioButton_5, 0, 4, 1, 1)
        self.radioButton_12 = QtWidgets.QRadioButton(Form)
        self.radioButton_12.setObjectName("radioButton_12")
        self.buttonGroup_2.addButton(self.radioButton_12)
        self.gridLayout_2.addWidget(self.radioButton_12, 1, 4, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.gridLayout_2.addWidget(self.radioButton_2, 0, 1, 1, 1)
        self.radioButton_20 = QtWidgets.QRadioButton(Form)
        self.radioButton_20.setObjectName("radioButton_20")
        self.buttonGroup_3.addButton(self.radioButton_20)
        self.gridLayout_2.addWidget(self.radioButton_20, 2, 5, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(Form)
        self.radioButton_6.setObjectName("radioButton_6")
        self.buttonGroup.addButton(self.radioButton_6)
        self.gridLayout_2.addWidget(self.radioButton_6, 0, 5, 1, 1)
        self.radioButton_19 = QtWidgets.QRadioButton(Form)
        self.radioButton_19.setObjectName("radioButton_19")
        self.buttonGroup_3.addButton(self.radioButton_19)
        self.gridLayout_2.addWidget(self.radioButton_19, 2, 4, 1, 1)
        self.radioButton_21 = QtWidgets.QRadioButton(Form)
        self.radioButton_21.setObjectName("radioButton_21")
        self.buttonGroup_3.addButton(self.radioButton_21)
        self.gridLayout_2.addWidget(self.radioButton_21, 2, 6, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.radioButton_15.setText(_translate("Form", "Желтый"))
        self.radioButton_13.setText(_translate("Form", "Красный"))
        self.radioButton_10.setText(_translate("Form", "Голубой"))
        self.radioButton_4.setText(_translate("Form", "Синий"))
        self.pushButton.setText(_translate("Form", "Сгенерировать флаг"))
        self.radioButton_7.setText(_translate("Form", "Оранжевый"))
        self.radioButton_16.setText(_translate("Form", "Зеленый"))
        self.radioButton_14.setText(_translate("Form", "Оранжевый"))
        self.radioButton_17.setText(_translate("Form", "Голубой"))
        self.radioButton_11.setText(_translate("Form", "Синий"))
        self.radioButton_18.setText(_translate("Form", "Синий"))
        self.radioButton_9.setText(_translate("Form", "Зеленый"))
        self.radioButton_8.setText(_translate("Form", "Желтый"))
        self.radioButton_3.setText(_translate("Form", "Голубой"))
        self.radioButton.setText(_translate("Form", "Желтый"))
        self.radioButton_5.setText(_translate("Form", "Розовый"))
        self.radioButton_12.setText(_translate("Form", "Розовый"))
        self.radioButton_2.setText(_translate("Form", "Зеленый"))
        self.radioButton_20.setText(_translate("Form", "Красный"))
        self.radioButton_6.setText(_translate("Form", "Красный"))
        self.radioButton_19.setText(_translate("Form", "Розовый"))
        self.radioButton_21.setText(_translate("Form", "Оранжевый"))

